name: Deploy Python Lambda

on:
  push:
    branches:
      - main
    paths:
      - "**.py" # Change to the file extension of the language that you are using.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Modify this to your desired AWS region

      - name: Deploy Modified Files
        run: |
          # Constants
          S3_BUCKET=tslambdabucket
          S3_KEY=lambda.zip
          LAMBDA_FUNCTION_NAME=ts-test-lambda-be
          aws s3 cp s3://$S3_BUCKET/$S3_KEY existing_lambda.zip
          unzip existing_lambda.zip -d lambda_env
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD); do
              if [[ $file == *.py ]]; then
                  mkdir -p lambda_env/$(dirname $file)
                  cp $file lambda_env/$file
                  echo "Copied $file to lambda_env/$file"
                  echo "Content of $file after copying:"
                  cat lambda_env/$file
              fi
          done
          cd lambda_env
          zip -r ../updated_lambda.zip .
          cd ..
          aws s3 cp updated_lambda.zip s3://$S3_BUCKET/$S3_KEY
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
          # Cleanup
          rm -r lambda_env
          rm existing_lambda.zip updated_lambda.zip
